// ============================
// CONFIGURATION & LANGUAGE DATA
// ============================

const AppConfig = {
  API_BASE_URL: "https://api.frdic.com/api/open/v1",
  
  // Available CSV vocabulary files
  csvFiles: [
    { filename: "0 Testword.csv", displayName: "Testword" },
    { filename: "33 Recette.csv", displayName: "33 Recette" },
    { filename: "35 Southwest France.csv", displayName: "35 Southwest France" }
  ],
  
  languageData: {
    fr: {
      code: "fr-FR",
      title: "Jeu de Reconnaissance Vocale",
      startBtn: "Commencer",
      passBtn: "Passer",
      volumeLabel: "Volume du Microphone",
      sayPhrase: "Dites la phrase...",
      great: "Excellent ! ",
      passed: "Passé ",
      finished: "Terminé !",
      greatJob: "Excellent travail !",
      noWords: "Aucun mot chargé.",
      noWordsAvailable: "Aucun mot disponible.",
      tryAgain: "Réessayez.",
      error: "Erreur. Réessayez.",
      micError: "Impossible d'accéder au microphone. Veuillez autoriser l'accès au microphone.",
      youSaid: "Vous avez dit :",
      words: [], // Will be loaded from CSV
      practicePlaceholder: "Entrez des mots séparés par des virgules ou des lignes...\nExemple: mot1, mot2, mot3\nOu:\nmot1\nmot2\nmot3\nOu format tableau: mot\t[phonétique]\texplication",
      practiceBtn: "Pratiquer ces mots",
      practiceSuccess: "mots chargés. Cliquez sur \"Commencer\" pour commencer !",
      practiceError: "Veuillez entrer des mots à pratiquer.",
      practiceNoWords: "Aucun mot valide trouvé. Veuillez vérifier votre saisie.",
      sayItBtn: "Dire",
      restartRecognitionBtn: "Redémarrer",
      flipBtnShow: "Voir le sens",
      flipBtnHide: "Masquer le sens",
      phoneticLabel: "Phonétique:",
      meaningLabel: "Signification:",
      speechError: "Erreur lors de la lecture du son. Veuillez réessayer.",
      speechNotSupported: "La synthèse vocale n'est pas prise en charge dans votre navigateur.",
      progressText: "{current} / {total} mots ({remaining} restants)",
      addTranslationPlaceholder: "Ajouter une traduction...",
      saveTranslationBtn: "Enregistrer",
      selectFolderBtn: "Sélectionner le dossier vocabulaire",
      csvSectionTitle: "Sélectionner une feuille de vocabulaire",
      csvSelectPlaceholder: "Sélectionner une feuille de vocabulaire...",
      loadCsvBtn: "Charger"
    },
    zh: {
      code: "zh-CN",
      title: "语音识别游戏",
      startBtn: "开始",
      passBtn: "跳过",
      volumeLabel: "麦克风音量",
      sayPhrase: "请说这句话...",
      great: "太好了",
      passed: "已跳过",
      finished: "完成！",
      greatJob: "做得很好！",
      noWords: "没有加载词语。",
      noWordsAvailable: "没有可用词语。",
      tryAgain: "再试一次。",
      error: "错误。再试一次。",
      micError: "无法访问麦克风。请允许麦克风访问。",
      youSaid: "您说的是：",
      practicePlaceholder: "输入单词，用逗号或换行分隔...\n示例: 单词1, 单词2, 单词3\n或:\n单词1\n单词2\n单词3\n或表格格式: 单词\t音标\t解释",
      practiceBtn: "练习这些",
      practiceSuccess: "个单词已加载。点击\"开始\"开始！",
      practiceError: "请输入要练习的单词。",
      practiceNoWords: "未找到有效单词。请检查您的输入。",
      sayItBtn: "发音",
      restartRecognitionBtn: "重新开始",
      flipBtnShow: "查看意思",
      flipBtnHide: "隐藏意思",
      phoneticLabel: "音标:",
      meaningLabel: "解释:",
      speechError: "播放声音时出错。请重试。",
      speechNotSupported: "您的浏览器不支持文本转语音。",
      progressText: "{current} / {total} 个单词（剩余 {remaining} 个）",
      addTranslationPlaceholder: "添加翻译...",
      saveTranslationBtn: "保存",
      selectFolderBtn: "选择词汇文件夹",
      csvSectionTitle: "选择词汇表",
      csvSelectPlaceholder: "选择词汇表...",
      loadCsvBtn: "加载",
      words: [
        "你好",
        "谢谢",
        "我要牛肉面",
        "不要",
        "晚上好",
        "晚安",
        "不客气",
        "没关系",
        "是的",
        "不是",
        "可能",
        "欢迎",
        "明天见",
        "你叫什么名字",
        "我叫",
        "很高兴认识你",
        "你好吗",
        "我很好",
        "在哪里",
        "多少钱",
        "我不明白",
        "你会说英语吗",
        "我很抱歉",
        "请慢一点",
        "请再说一遍",
        "我饿了",
        "我渴了",
        "谢谢你的帮助"
      ],
      pinyin: {
        "你好": "nǐ hǎo",
        "谢谢": "xiè xie",
        "我要牛肉面": "wǒ yào niú ròu miàn",
        "不要": "bú yào",
        "晚上好": "wǎn shang hǎo",
        "晚安": "wǎn ān",
        "不客气": "bú kè qì",
        "没关系": "méi guān xi",
        "是的": "shì de",
        "不是": "bú shì",
        "可能": "kě néng",
        "欢迎": "huān yíng",
        "明天见": "míng tiān jiàn",
        "你叫什么名字": "nǐ jiào shén me míng zi",
        "我叫": "wǒ jiào",
        "很高兴认识你": "hěn gāo xìng rèn shi nǐ",
        "你好吗": "nǐ hǎo ma",
        "我很好": "wǒ hěn hǎo",
        "在哪里": "zài nǎ lǐ",
        "多少钱": "duō shao qián",
        "我不明白": "wǒ bù míng bai",
        "你会说英语吗": "nǐ huì shuō yīng yǔ ma",
        "我很抱歉": "wǒ hěn bào qiàn",
        "请慢一点": "qǐng màn yì diǎn",
        "请再说一遍": "qǐng zài shuō yí biàn",
        "我饿了": "wǒ è le",
        "我渴了": "wǒ kě le",
        "谢谢你的帮助": "xiè xie nǐ de bāng zhù"
      }
    }
  }
};

